Ian
Rahmatuldani/dicoding-capstone pull request #1
Opened 2023-10-19 06:39 UTC by septiana25

call api to render component card

2023-10-19 08:42 UTC, Rahmatuldani requested changes
sudah bagus, namun dibagian pages/index.jsx jangan hapus component lain ya. perbaiki dulu @septiana25

2023-10-19 08:42 UTC, Rahmatuldani commented on src/router.jsx
> +                <Route path='/ian' element={<Ian/>}/>
oke, sudah bisa bikin routing sesuai yang diminta

2023-10-19 08:42 UTC, Rahmatuldani commented on src/router.jsx
> +import Ian from './pages/ian';
sudah bisa import ke bagian component pages

2023-10-19 08:42 UTC, Rahmatuldani commented on src/pages/index.jsx
> -    Dani,
oke, sudah bisa masukin ke index component namum jangan hapus yang lama. soalnya nanti ada error di route.jsx

2023-10-19 08:42 UTC, Rahmatuldani commented on src/pages/ian.jsx
> +                                <Card.Text >{strLimit(item.description).limit(100, '...').get()}</Card.Text>
bagus, pakai package lain untuk membantu memperpendek deskripsi

2023-10-20 03:08 UTC, septiana25 commented on src/pages/index.jsx
> -    Dani,
baik akan diperbaiki

2023-10-20 03:16 UTC, septiana25 commented on src/pages/ian.jsx
> +                                <Card.Text >{strLimit(item.description).limit(100, '...').get()}</Card.Text>
terimakasih

2023-10-20 03:37 UTC, septiana25 commented on src/pages/index.jsx
> -    Dani,
Perbaikan sudah dilakukan, mohon periksa kembali

2023-10-20 03:38 UTC, septiana25 commented
Perbaikan sudah dilakukan, mohon periksa kembali

2023-10-21 10:51 UTC, Rahmatuldani approved these changes

2023-10-21 10:51 UTC, merged